[pytest]
DJANGO_SETTINGS_MODULE = patrimoinehub.settings
python_files = tests.py test_*.py *_tests.py
addopts = -ra --tb=short --reuse-db
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
