# Generated by Django 5.0.6 on 2026-05-07 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('period', models.CharField(choices=[('prehistoric', 'Prehistoric'), ('numidian', 'Numidian'), ('roman', 'Roman'), ('medieval', 'Medieval'), ('ottoman', 'Ottoman'), ('colonial', 'Colonial'), ('contemporary', 'Contemporary')], db_index=True, max_length=20)),
                ('architectural_type', models.CharField(choices=[('mosque', 'Mosque'), ('medersa', 'Medersa'), ('casbah', 'Casbah / Medina'), ('palace', 'Palace'), ('fortification', 'Fortification'), ('church', 'Church'), ('synagogue', 'Synagogue'), ('mausoleum', 'Mausoleum'), ('traditional_house', 'Traditional house'), ('archaeological_site', 'Archaeological site'), ('other', 'Other')], db_index=True, max_length=24)),
                ('wilaya', models.CharField(db_index=True, max_length=80)),
                ('commune', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('classification_level', models.CharField(choices=[('unesco', 'UNESCO World Heritage'), ('national', 'National'), ('regional', 'Regional'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name_fr',),
                'indexes': [models.Index(fields=['period', 'architectural_type'], name='heritage_he_period_14c114_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='heritage.heritageresource')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('lead', 'Project lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer')], default='contributor', max_length=14)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='heritage.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at',),
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='heritage.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'updated_at'], name='heritage_pr_status_59beec_idx'),
        ),
    ]
