# Generated by Django 5.0.6 on 2026-05-07 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0001_initial'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('general', 'General'), ('conflict', 'Editorial conflict'), ('review', 'Review')], default='general', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_discussions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='pages.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='heritage.project')),
                ('related_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='pages.pageversion')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_proposal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion_messages', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.discussion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='discussions.message')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConflictVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_votes', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='discussions.discussion')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='discussions.message')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['project', 'status'], name='discussions_project_091728_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['type', 'status'], name='discussions_type_d0bab5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['discussion', 'created_at'], name='discussions_discuss_5c804a_idx'),
        ),
        migrations.AddConstraint(
            model_name='conflictvote',
            constraint=models.UniqueConstraint(fields=('discussion', 'voter'), name='one_vote_per_user_per_discussion'),
        ),
    ]
