# Generated by Django 5.0.6 on 2026-05-07 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('heritage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], db_index=True, max_length=10)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=120)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='heritage.project')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_json', models.JSONField(blank=True, default=dict)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('body_text', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='accounts.discipline')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='heritage.heritageresource')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_annotations', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='media_app.media')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'created_at'], name='media_app_m_media_t_fe0830_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['media', 'created_at'], name='media_app_a_media_i_bb3797_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['resource', 'created_at'], name='media_app_a_resourc_71203e_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('media__isnull', False), ('resource__isnull', True)), models.Q(('media__isnull', True), ('resource__isnull', False)), _connector='OR'), name='annotation_target_required'),
        ),
    ]
