# Generated by Django 5.0.6 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='media',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
